# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 254e25275263445fcb7ab9127d43a6b7b77ad5f4a8dff8e6e18e6afdb2c24afff57bb85bf943adaa6fc6a43384814e64654b382c076317e0e489532ae15bd917
  twitter_key: <%= ENV['TWITTER_KEY'] %>
  twitter_secret: <%= ENV['TWITTER_SECRET'] %>

test:
  secret_key_base: 113f5d37c8bcbe6a8716e44e96245443b9f46d01872c16cc1f1e42bcf81e821dc3870417fe9bbc9038e6d2e7e0d9aab0985c7d5b13242c3374f63491479641a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
